(()=>{"use strict";
const C=window.PopPartyCore,$=id=>document.getElementById(id),STORE="pop-party-save-v1";
const faces=["●","✿","☻","✦","♥","☀"];
let progress=loadProgress(),level=1,board=[],moves=25,score=0,collected={},busy=false,combo=0,seed=Date.now()>>>0,config,toastTimer,modalAction=null;
function loadProgress(){try{return C.sanitiseProgress(JSON.parse(localStorage.getItem(STORE)));}catch{return C.newProgress();}}
function save(){try{localStorage.setItem(STORE,JSON.stringify(progress));}catch{}}
function randomSeed(){seed=(seed+0x9e3779b9)>>>0;return seed;}
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),1700);}
function startLevel(n){level=Math.max(1,Math.min(C.MAX_LEVEL,n));config=C.levelConfig(level);moves=config.moves;score=0;combo=0;collected={};busy=false;board=C.createBoard(level,randomSeed());$("level-number").textContent=level;$("goal-title").textContent="Collect "+config.targets.reduce((s,t)=>s+t.count,0)+" pals";$("goal-subtitle").textContent=level<5?"Big groups make bigger pops!":"Watch your moves — plan those combos!";render();updateHud();closeModal();}
function render(){const el=$("board");el.innerHTML="";board.forEach((tile,i)=>{const b=document.createElement("button");b.type="button";b.className="tile "+(tile===null?"empty":typeof tile==="string"?"power-"+tile:"c"+tile);b.setAttribute("role","gridcell");b.setAttribute("aria-label",tile===null?"Empty":typeof tile==="string"?tile+" power-up":faces[tile]+" character");b.dataset.index=i;if(tile===null)b.disabled=true;else{const f=document.createElement("span");f.className="face";f.textContent=typeof tile==="string"?(tile==="rocket"?"➜":tile==="bomb"?"✹":"🌈"):faces[tile];b.appendChild(f);b.addEventListener("click",()=>tapTile(i));}el.appendChild(b);});}
function updateHud(){const stars=C.starsFor(score,config.stars);$("moves-left").textContent=moves;$("coin-count").textContent=progress.coins;$("progress-fill").style.width=Math.min(100,score/config.stars[2]*100)+"%";$("level-stars").textContent=[0,1,2].map(i=>i<stars?"★":"☆").join(" ");$("goals").innerHTML="";config.targets.forEach(t=>{const got=Math.min(t.count,collected[t.colour]||0),chip=document.createElement("div");chip.className="goal-chip"+(got>=t.count?" done":"");const face=document.createElement("span");face.className="goal-mini";face.textContent=faces[t.colour];const count=document.createElement("span");count.textContent=got+"/"+t.count;chip.append(face,count);$("goals").appendChild(chip);});["rocket","bomb"].forEach(k=>$(k+"-count").textContent=(progress.boosters[k]||0)+" owned");}
function targetComplete(){return config.targets.every(t=>(collected[t.colour]||0)>=t.count);}
function tapTile(i){if(busy)return;if(typeof board[i]==="string"){clearGroup([i],board[i]);return;}const group=C.groupAt(board,i);if(group.length<2){toast("Find a matching group of 2 or more!");return;}const power=group.length>=9?"rainbow":group.length>=5?"bomb":group.length>=4?"rocket":null;if(power){createPower(group,power);return;}clearGroup(group,null);}
function createPower(group,power){if(busy)return;busy=true;const at=group[Math.floor(group.length/2)];group.forEach(i=>{if(i!==at){const tile=$("board").querySelector('[data-index="'+i+'"]');if(tile)tile.classList.add("popping");const v=board[i];if(typeof v==="number")collected[v]=(collected[v]||0)+1;board[i]=null;}});score+=C.scoreForGroup(group.length);moves--;combo++;board[at]=power;const tile=$("board").querySelector('[data-index="'+at+'"]');if(tile)tile.classList.add("popping");updateHud();toast(power==="rainbow"?"RAINBOW PAL!":"Power-up created!");setTimeout(()=>{board=C.applyGravity(board);board=C.refill(board,level,randomSeed());busy=false;render();updateHud();if(targetComplete())winLevel();else if(moves<=0)loseLevel();},240);}
function clearGroup(indices,power){if(busy)return;busy=true;const all=new Set(indices);if(power==="rocket"){const row=Math.floor(indices[0]/C.COLS);for(let x=0;x<C.COLS;x++)all.add(row*C.COLS+x);}else if(power==="bomb"){const centre=indices[0],cx=centre%C.COLS,cy=Math.floor(centre/C.COLS);for(let y=Math.max(0,cy-1);y<=Math.min(C.ROWS-1,cy+1);y++)for(let x=Math.max(0,cx-1);x<=Math.min(C.COLS-1,cx+1);x++)all.add(y*C.COLS+x);}else if(power==="rainbow"){const counts=Array(C.COLOURS).fill(0);board.forEach(v=>{if(typeof v==="number")counts[v]++;});const colour=counts.indexOf(Math.max(...counts));board.forEach((v,i)=>{if(v===colour)all.add(i);});}
const valid=[...all].filter(i=>board[i]!==null&&board[i]!==undefined);if(!valid.length){busy=false;return;}const n=valid.length;valid.forEach(i=>{const tile=$("board").querySelector('[data-index="'+i+'"]');if(tile)tile.classList.add("popping");const value=board[i];if(typeof value==="number")collected[value]=(collected[value]||0)+1;board[i]=null;});score+=C.scoreForGroup(n)*(combo>0?combo+1:1);combo++;moves--;if(progress.sound&&navigator.vibrate&&progress.vibration)navigator.vibrate(12);$("combo-label").textContent=combo>1?"🔥 "+combo+"x COMBO!":"Nice pop!";updateHud();setTimeout(()=>{board=C.applyGravity(board);board=C.refill(board,level,randomSeed());render();const cascade=findCascade();if(cascade.length){setTimeout(()=>clearGroup(cascade,null),100);return;}busy=false;updateHud();if(targetComplete())winLevel();else if(moves<=0)loseLevel();else if(!C.hasMove(board)){board=C.createBoard(level,randomSeed());render();toast("Fresh board — keep going!");}},240);}
function findCascade(){for(let i=0;i<board.length;i++){const g=C.groupAt(board,i);if(g.length>=5)return g;}return[];}
function winLevel(){const stars=C.starsFor(score,config.stars),key=String(level),old=progress.levels[key]||{stars:0,score:0},earned=Math.max(1,stars)*10+Math.floor(score/100);progress.levels[key]={stars:Math.max(old.stars,stars),score:Math.max(old.score,score)};progress.stars=Object.values(progress.levels).reduce((s,v)=>s+(v.stars||0),0);progress.coins+=earned;progress.unlocked=Math.max(progress.unlocked,Math.min(C.MAX_LEVEL,level+1));save();updateHud();showModal("🎉","Pop-tastic!","You completed level "+level+" and saved the day!",'<div class="modal-stats"><div class="modal-stat"><span>'+("★".repeat(stars)||"☆")+'</span>'+stars+' stars</div><div class="modal-stat"><span>🪙 '+earned+'</span>coins earned</div></div>',"Next level",()=>startLevel(Math.min(C.MAX_LEVEL,level+1)));}
function loseLevel(){showModal("🫣","So close!","Your pals need a few more pops. Try a different plan and go for a bigger combo.","","Try again",()=>startLevel(level));}
function showModal(emoji,title,copy,extra,primary,action,secondary){$("modal-emoji").textContent=emoji;$("modal-title").textContent=title;$("modal-copy").textContent=copy;$("modal-extra").innerHTML=extra||"";$("modal-primary").textContent=primary||"Keep popping!";$("modal-secondary").classList.toggle("hidden",!secondary);$("modal-secondary").textContent=secondary||"Try again";modalAction=action;$("modal-backdrop").classList.remove("hidden");}
function closeModal(){$("modal-backdrop").classList.add("hidden");}
$("modal-primary").addEventListener("click",()=>{const a=modalAction;closeModal();if(a)a();});$("modal-secondary").addEventListener("click",()=>{closeModal();startLevel(level);});$("modal-close").addEventListener("click",closeModal);
function showMap(){let html='<div class="map-list">';for(let i=Math.max(1,level-4);i<=Math.min(progress.unlocked,level+7);i++){const done=progress.levels[i];html+='<button class="map-level '+(i===level?"current":"")+'" data-level="'+i+'">'+i+(done?"<br>"+("★".repeat(done.stars||0)):"")+'</button>';}html+='</div>';showModal("🗺️","Poppy Trails","Choose any level you've unlocked.",html,"Back to game",()=>{});$("modal-extra").querySelectorAll("[data-level]").forEach(b=>b.addEventListener("click",()=>startLevel(Number(b.dataset.level))));}
$("map-button").addEventListener("click",showMap);
function settings(){showModal("⚙️","Your settings","Make Pop Party feel just right.",'<label class="setting-row">Sound effects <input id="setting-sound" type="checkbox" '+(progress.sound?"checked":"")+'></label><label class="setting-row">Vibration <input id="setting-vibration" type="checkbox" '+(progress.vibration?"checked":"")+'></label><label class="setting-row">Reset all progress <button id="reset-progress" class="secondary-button" style="width:auto;margin:0;padding:7px 10px">Reset</button></label>',"Save settings",()=>{progress.sound=$("setting-sound").checked;progress.vibration=$("setting-vibration").checked;save();toast("Settings saved");});$("reset-progress").addEventListener("click",()=>showModal("⚠️","Start fresh?","This permanently resets your local stars, coins and levels.","","Reset progress",()=>{progress=C.newProgress();save();startLevel(1);}));}
$("settings-button").addEventListener("click",settings);
document.querySelectorAll("[data-power]").forEach(b=>b.addEventListener("click",()=>usePower(b.dataset.power)));
function usePower(type){if(busy)return;if(type==="shuffle"){if((progress.boosters.shuffle||0)<=0&&progress.coins<25){toast("Earn coins by winning levels!");return;}if((progress.boosters.shuffle||0)>0)progress.boosters.shuffle--;else progress.coins-=25;board=C.createBoard(level,randomSeed());save();render();updateHud();toast("New possibilities!");return;}if((progress.boosters[type]||0)<=0){if(progress.coins>=25)showModal("🪙","A little boost?","Trade 25 coins for one "+type+".","","Get boost · 25 🪙",()=>{progress.coins-=25;progress.boosters[type]=(progress.boosters[type]||0)+1;save();updateHud();usePower(type);});else toast("No boosts left — earn coins by winning!");return;}progress.boosters[type]--;save();const i=board.findIndex(v=>v!==null);if(i<0)return;clearGroup([i],type);updateHud();}
function init(){progress.unlocked=Math.max(1,progress.unlocked);save();startLevel(Math.min(progress.unlocked,Math.max(1,Number(progress.lastLevel)||1)));if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("./sw.js").catch(()=>{});}
init();
})();