(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.PopPartyCore=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){
  "use strict";
  const COLS=8,ROWS=9,COLOURS=6,MAX_LEVEL=5000;
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  function rng(seed){let s=(seed>>>0)||1;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
  function createBoard(level,seed){const rand=rng((seed||level*2654435761)>>>0),board=Array(ROWS*COLS).fill(null);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){let options=Array.from({length:COLOURS},(_,i)=>i);if(x>1&&board[y*COLS+x-1]===board[y*COLS+x-2])options=options.filter(c=>c!==board[y*COLS+x-1]);if(y>1&&board[(y-1)*COLS+x]===board[(y-2)*COLS+x])options=options.filter(c=>c!==board[(y-1)*COLS+x]);board[y*COLS+x]=options[Math.floor(rand()*options.length)];}if(!hasMove(board)){board[0]=board[1];if(board[1]===board[2])board[2]=(board[1]+1)%COLOURS;if(board[8]===board[16])board[8]=(board[0]+1)%COLOURS;}return board;}
  function neighbours(index){const x=index%COLS,y=Math.floor(index/COLS),out=[];if(x>0)out.push(index-1);if(x<COLS-1)out.push(index+1);if(y>0)out.push(index-COLS);if(y<ROWS-1)out.push(index+COLS);return out;}
  function groupAt(board,index){if(!board||index<0||index>=board.length||board[index]===null||board[index]===undefined||board[index]<0)return[];const colour=board[index],seen=new Set([index]),stack=[index];while(stack.length){for(const n of neighbours(stack.pop()))if(!seen.has(n)&&board[n]===colour){seen.add(n);stack.push(n);}}return [...seen].sort((a,b)=>a-b);}
  function hasMove(board){for(let i=0;i<board.length;i++)if(groupAt(board,i).length>=2)return true;return false;}
  function applyGravity(board){const next=Array(ROWS*COLS).fill(null);for(let x=0;x<COLS;x++){let y=ROWS-1;for(let from=ROWS-1;from>=0;from--){const v=board[from*COLS+x];if(v!==null&&v!==undefined){next[y*COLS+x]=v;y--;}}}return next;}
  function refill(board,level,seed){const rand=rng((seed+level*104729)>>>0),next=board.slice();for(let i=0;i<next.length;i++)if(next[i]===null||next[i]===undefined)next[i]=Math.floor(rand()*COLOURS);return next;}
  function levelConfig(level){const n=Math.max(1,Math.floor(level));const a=n<5?12+n*2:Math.min(48,18+Math.floor(n*1.5));return{level:n,moves:clamp(25-Math.floor((n-1)/5),18,25),targets:[{colour:(n-1)%COLOURS,count:a},{colour:(n+2)%COLOURS,count:Math.max(0,Math.floor(a*.45)-Math.floor(n/10))}],stars:[Math.round(a*1.2),Math.round(a*1.8),Math.round(a*2.6)]};}
  function scoreForGroup(size){return size*10+Math.max(0,size-2)*Math.max(0,size-2)*5;}
  function starsFor(score,thresholds){return score>=thresholds[2]?3:score>=thresholds[1]?2:score>=thresholds[0]?1:0;}
  function newProgress(){return{unlocked:1,coins:50,stars:0,levels:{},boosters:{rocket:2,bomb:1,shuffle:1},sound:true,vibration:true};}
  function sanitiseProgress(raw){const base=newProgress();if(!raw||typeof raw!=="object")return base;return{...base,...raw,unlocked:clamp(Number(raw.unlocked)||1,1,MAX_LEVEL),coins:clamp(Number(raw.coins)||0,0,999999999),stars:clamp(Number(raw.stars)||0,0,MAX_LEVEL*3),levels:raw.levels&&typeof raw.levels==="object"?raw.levels:{},boosters:{...base.boosters,...(raw.boosters||{})},sound:raw.sound!==false,vibration:raw.vibration!==false};}
  return{COLS,ROWS,COLOURS,MAX_LEVEL,rng,createBoard,neighbours,groupAt,hasMove,applyGravity,refill,levelConfig,scoreForGroup,starsFor,newProgress,sanitiseProgress};
});